# Set strict execution policy for the current session to allow running this script
$OptionalSign = $null
if ($PSVersionTable.PSVersion.Major -ge 5) {
    $currentPolicy = Get-ExecutionPolicy -Scope Process
    if ($currentPolicy -ne "Bypass" -and $currentPolicy -ne "Unrestricted") {
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
    }
}

# 1. ENVIRONMENT PATH FIX
# Add the current build directory to the absolute top of PATH so local DLLs are found first, 
# then add MSYS2 binaries as a fallback.
$env:PATH = "$(Get-Location)\build;C:\msys64\mingw64\bin;" + $env:PATH


# 2. CONFIGURE PROJECT
# If the build directory does not exist, create it and configure the project using Ninja
if (-not (Test-Path "build")) {
    Write-Host "Build folder not found. Creating and configuring the project via Ninja..." -ForegroundColor Cyan
    # Using Ninja generator to match your VS Code setup
    cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Debug
} else {
    Write-Host "Build folder already exists. Skipping initial CMake configuration." -ForegroundColor Green
}

# 3. BUILD PROJECT
Write-Host "Compiling the project..." -ForegroundColor Yellow
cmake --build build

# 4. EXECUTE APPLICATION
# Check if the compilation completed successfully (exit code 0)
if ($LASTEXITCODE -eq 0) {
    Write-Host "Build successful! Launching the application..." -ForegroundColor Green
    
    # Executing the exact target binary generated by CMake
    .\build\MIYOO_SQUARE.exe
} else {
    Write-Host "Build failed! Please fix the compilation errors above and try again." -ForegroundColor Red
}